project:
  type: website
  output-dir: docs

website:
  title: "Biología de Sistemas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analisis_topo.qmd
        text: Análisis y Topología (I)
      - href: analisis_topo_2.qmd
        text: Análisis y Topología (II)
      - href: minimal_analysis.qmd
        text: Minimal Análisis
      - href: clustering.qmd
        text: Clustering
      - href: clustering_2.qmd
        text: Clustering Enlaces
      - href: func_enric.qmd
        text: Enriquecimiento Funcional
      - href: coexp.qmd
        text: Coexpression Analysis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
