project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - minimal_analysis.qmd
    - analisis_topo.qmd
    # - analisis_topo_2.qmd
    # - clustering.qmd
    # - clustering_2.qmd
    # - func_enric.qmd
    # - coexp.qmd
    # - recreate_aa.qmd

website:
  title: "Biología de Sistemas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: minimal_analysis.qmd
        text: Minimal Análisis
      - href: analisis_topo_1.qmd
        text: Análisis y Topología (I)
      # - href: analisis_topo_2.qmd
      #   text: Análisis y Topología (II)
      # - href: clustering.qmd
      #   text: Clustering
      # - href: clustering_2.qmd
      #   text: Clustering Enlaces
      # - href: func_enric.qmd
      #   text: Enriquecimiento Funcional
      # - href: coexp.qmd
      #   text: Coexpression Analysis
      # - href: recreate_aa.qmd
      #   text: Build a Pathway

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
